sudo: false

language: c

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - clang

install:
  - make

script:
  - make check

notifications:
  email: false
